# Dataset configuration
dataset = {
    "path": "./data",
    "path_raw": "raw",
    "path_processed": "processed",
    "path_fastdup": "fastdup",
    "path_training": "train",
    "path_test": "test",
    "classes": ["macarrones", "pizza", "tiramisu"],
    "classes_keywords": {
        "macarrones": [
            "macarrones",
            "macarrones receta",
            "macarrones con queso",
            "macarrones con queso receta",
            "macarrones con atun",
            "macarrones con atun receta",
            "macarrones con carne",
            "macarrones con carne receta",
            "macarrones con pollo",
            "macarrones con pollo receta",
            "macarrones con salchichas",
            "macarrones con salchichas receta",
            "macarrones con tomate",
            "macarrones con tomate receta",
            "macarrones con camarones",
            "macarrones con camarones receta",
            "macarrones con lentejas",
            "macarrones con lentejas receta",
            "macarrones veganos",
            "macarrones veganos receta",
            "macarrones vegetarianos",
            "macarrones vegetarianos receta",
            "macarrones con verduras",
            "macarrones con verduras receta",
            "macarrones con queso kraft",
            "macarrones con queso kraft receta",
            "macarrones hervidos",
            "macarrones hervidos receta",
            "macarrones integrales",
            "macarrones integrales receta",
            "macarrones al pesto",
            "macarrones al pesto receta",
            "macarrones con gambas",
            "macarrones con gambas receta",
            "macarrones al horno",
            "macarrones al horno receta",
            "macarrones al horno gratinados",
            "macarrones al horno con queso",
            "macarrones al horno huevo",
            "macarrones al horno con bechamel",
            "macarrones al horno con atun",
            "macarrones al horno con tomate",
            "macarrones al horno con carne picada",
            "macarrones gratinados",
            "macarrones con bonito",
            "macarrones con bonito receta",
            "macarrones a la carbonara",
            "macarrones a la carbonara receta",
            "macarrones con chorizo",
            "macarrones con chorizo receta",
            "macarrones fitness",
            "macarrones fitness receta",
            "macarrones receta rapida",
            "macarrones con salsa",
            "macarrones microondas",
            "macarrones microondas receta",
            "macarrones thermomix",
            "macarrones thermomix receta",
            "macaroni",
            "macaroni and cheese",
            "macaroni and tuna",
            "macaroni and meat",
            "macaroni and chiken",
            "macaroni and sausage",
            "macaroni and tomatoes",
            "macaroni and tomatoes old fashioned"
        ],
        "pizza": [
            "pizza",
            "pizza hawaiana",
            "pizza con piña",
            "pizza con peperoni",
            "pizza con queso",
            "pizza con champiñones",
            "pizza con kiwi",
            "pizza carbonara",
            "pizza de jamon y queso",
            "pizza cuatro quesos",
            "pizza barbacoa",
            "pizza pulled pork",
            "pizza margarita",
            "pizza marinera",
            "pizza vegetariana",
            "pizza capricciosa",
            "pizza napolitana",
            "pizza de trufa",
            "pizza siciliana",
            "pizza de prosciutto",
            "pizza española",
            "pizza mexicana",
            "pizza de cajun",
            "pizza de albondigas",
            "Hawaiian pizza",
            "pineapple pizza",
            "pepperoni pizza",
            "cheese pizza",
            "mushroom pizza",
            "kiwi pizza",
            "carbonara pizza",
            "ham and cheese pizza",
            "four cheese pizza",
            "barbecue pizza",
            "pulled pork pizza",
            "margarita pizza",
            "seafood pizza",
            "vegetarian pizza",
            "capricciosa pizza",
            "Neapolitan pizza",
            "truffle pizza",
            "Sicilian pizza",
            "prosciutto pizza",
            "Spanish pizza",
            "Mexican pizza",
            "cajun pizza",
            "meatball pizza",
            "pizza artesanal",
            "pizza de tocino",
            "pizza con orilla de queso",
            "pizza con borde de queso",
            "pizza masa fina",
            "pizza con carne adobada",
            "pizza de carne asada"
        ],
        "tiramisu": [
            "tiramisu",
            "tiramisu en copa",
            "tiramisu casero",
            "tiramisu de fresa",
            "tiramisu italiano",
            "tiramisu en vaso",
            "tiramisu classico",
            "tiramisu receta facil",
            "tiramisu receta",
            "tiramisu sin huevo",
            "tiramisu thermomix",
            "tiramisu de chocolate",
            "tiramisu de frutos rojos",
            "tiramisu de frutas",
            "tiramisu de maracuya",
            "tiramisu recette",
            "tiramisu mousse",
            "pastel de tiramisu",
            "bizcocho de tiramisu",
            "tarta de tiramisu",
            "tiramisu mascarpone",
            "tiramisu mascarpone cheesecake",
            "tiramisu mercadona",
            "foto tiramisu",
            "tiramisu con pavesini",
            "tiramisu con rebandas de pan integral",
            "tiramisu sin crema",
            "tiramisu en lima",
            "tiramisu en buche",
            "tiramisu en verrine",
            "tiramisu en español",
            "tiramisu historia",
            "tiramisu recette",
            "tiramisu con fragole",
            "tiramisu con queso crema",
            "tiramisu con galletas maria",
            "tiramisu sin huevo",
            "tiramisu sin gluten",
            "tiramisu sin horno",
            "tiramisu sin azucar",
            "tiramisu sin mascarpone",
            "tiramisu sin tacc",
            "tiramisu con pandoro",
            "tiramisu con panna",
            "tiramisu con queso philadelphia",
            "tiramisu con uova pastorizzate"
        ]
    },
    "classes_num_images": 2000,
    "classes_images_extension": "jpg",
    "classes_images_split_ratio": 0.80,
    "fastdup": {
        "export": True,
        "amount_of_runs": 3
    }
}

# Model configuration
model = {
    "path": "./data",
    "path_models": "models",
    "path_classes": "./data/processed",
    "name": "svc_model.joblib",
    "grid_search": {
        "C": [4, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
        "kernel": ["rbf", "linear", "poly"]
    }
}
